source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'
gem 'mysql2'
gem 'sqlite3'
gem 'nokogiri'
gem 'rufus-scheduler'
gem 'highscore'
gem 'sanitize'
gem 'metainspector'
gem 'activerecord'
gem 'rumoji'
