source 'https://rubygems.org'
ruby '2.3.1'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'
gem 'mysql2'
gem 'sqlite3', :group => [:development, :test]
gem 'nokogiri'
gem 'rufus-scheduler'
gem 'highscore'
gem 'sanitize'
gem 'metainspector'
gem 'activerecord'
gem 'rumoji', :git => 'https://github.com/mwunsch/rumoji.git'
gem 'rake'
gem 'rack-test'
gem 'test-unit'
gem 'i18n'
gem 'apnotic'
