development:
  db_adapter: 'sqlite3'
  db_database: 'news.db'

production:
  db_adapter: 'mysql2'
  db_host: 'localhost'
  db_username: 'root'
  db_password: ''
  db_database: 'canillitapp'

test:
  db_adapter: 'sqlite3'
  db_database: 'test.db'
